server:
  port: 8080

spring:
  application:
    name: relive-app

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
