server:
  port: 8080
  servlet:
    session:
      cookie:
        name: CLIENT-SESSION

spring:
  security:
    cas:
      client:
        # CAS 服务器的基本 URL，指向 CAS 认证服务器
        cas-server-url: http://localhost:8443/cas
        # CAS 服务器的登录 URL，指向 CAS 认证登录页面
        cas-server-login-url: http://localhost:8443/cas/login
        # 当前应用需要进行 CAS 验证的服务 URL
        service: http://localhost:8080/login/cas



logging:
  level:
    root: INFO
    org.springframework.security: debug
    org.jasig.cas.client: debug
